# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a273bab0fce4180c516a94746f6e9cc8288d2e3d90f355d99a2da20a8adba511329671ec39a45da5cfe9257d93df06ffa8c47eefd6358d75328a41d5bcb5619

test:
  secret_key_base: 018939719dc768090a1cb0cfd5753b7d21b750804afc81dbd88802c79f397b4f669b9da0c39731198fab3a215829170dead877d5d07a354120b29824a2ba4c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
